# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
      - job: job1
        steps:
        - script: echo Hello, Job1!
          displayName: 'Run a one-line script'

      - job: job2
        steps:
        - script: echo Hello, Job2!
          displayName: 'Run a one-line script' 
- stage: dev_deploy
  dependsOn: build
  jobs:
      - job: job1
        steps:
        - script: echo Hello, Job1!
          displayName: 'Run a one-line script'
    
      - job: job2
        steps:
        - script: echo Hello, Job2!
        displayName: 'Run a one-line script' 
- stage: test_deploy
  dependsOn: build
  jobs:
      - job: job1
        steps:
        - script: echo Hello, Job1!
          displayName: 'Run a one-line script'

      - job: job2
        steps:
        - script: echo Hello, Job2!
          displayName: 'Run a one-line script' 
- stage: prod_test_deploy
  dependsOn:
    - test_deploy
    - dev_deploy
  jobs:
      - job: job1
        steps:
        - script: echo Hello, Job1!
          displayName: 'Run a one-line script'
    
      - job: job2
        steps:
        - script: echo Hello, Job2!
          displayName: 'Run a one-line script' 
